### PR TITLE
Set body only for supported request types

### PR DESCRIPTION
**Pull request by sjurgis**
request.setBody('') automatically turns get requests into POST
setting content type on blank body doesn't make sense either

### CODE REVIEW

**Comment by sjurgis** [comment]
It's quite a nasty bug guys :)

**Comment by manzanit0** [comment]
True @sjurgis , thanks for the heads up man and the PR! I can't believe we missed those.

**Comment by sjurgis** [comment]
@Manzanit0 you wanna put some sort of licence on this?

**Comment by manzanit0** [comment]
@sjurgis I should, right? I'm not very experienced on this. Any recommendations?

**Pull request merged**
